---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue1-attacker
  labels:
    app: ueransim
    component: ue
    name: ue1
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
      name: ue1
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
        name: ue1
    spec:
      containers:
      - image: ghcr.io/niloysh/ueransim:v3.2.6
        imagePullPolicy: Always
        name: ue
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: [ "/bin/bash", "-c", "--" ]
        args:
          - |
            if [ "$DEBUG_MODE" = "true" ]; then
              while true; do sleep 30; done;
            else
              /ueransim/config/wrapper.sh
            fi
        env:
          - name: DEBUG_MODE
            value: "false"
        volumeMounts:
        - mountPath: /ueransim/config
          name: ue-volume
        resources:
          requests:
            memory: "2048Mi" # "2048Mi"
            cpu: "1000m" # "4000m"
          limits:
            memory: "4096Mi" # "4096Mi"
            cpu: "3000m" # "5000m""
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: ue-volume
        configMap:
          name: ue1-configmap
          items:
          - key: free5gc-ue.yaml
            path: free5gc-ue.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0755
          - key: wrapper-debug.sh
            path: wrapper-debug.sh
            mode: 0755